config/routes.rb
PlanAga::Application.routes.draw do
  devise_for :users, controllers: {
               sessions: 'sessions',
               registrations: 'admin/users/new',
            }

  # TinymceFm
  mount TinymceFm::Engine => "/tinymce_fm"

  # constraints :subdomain => 'admin' do
  namespace :admin do
    # scope :module => 'admin', :as => 'admin' do
      # defaults :subdomain => 'admin' do

        root :to => 'dashboard#index'
        resources :users do
          member do
            get :history
          end
        end
        resource :profile
        resources :aga_plans
        resources :aga_responsibles
        resources :aga_challenges do
          collection do
            # get 'general_info'
            # post 'save_general_info'
          end
          resources :aga_actions
        end
        resources :aga_informations
        resources :aga_timeline_items do
          member do
            get 'get_challenge_actions'
          end
        end
        resources :aga_documents
      # end
    # end
  end

  # constraints :subdomain => 'alianza' do
  #   scope :module => 'alianza', :as => 'alianza' do
  #     defaults :subdomain => 'alianza' do
        # root_path = 'aga_challenges#index'
        scope "(:plan)" do
          resources :documents, only: [:index]
          resources :aga_challenges, only: [:index] do
            resources :aga_actions, only: [:show]
            collection do
              get 'general'
              get 'information'
            end
          end
        end
        root :to => 'aga_challenges#index'
        get '/:plan', to: 'aga_challenges#index'
  #     end
  #   end
  # end

  # root :to => 'alianza/aga_challenges#index'
end

app/models/aga_document.rb
class AgaDocument < ActiveRecord::Base
  attr_accessible :title, :description

  belongs_to :user

  attr_accessible :datafile
  has_attached_file :datafile

  validates :title, presence: true
  validates_length_of :description, :maximum => 250, :too_long => "Debe contener un maximo de 250 caracteres."

end

app/controllers/admin/aga_documents_controller.rb
class Admin::AgaDocumentsController < AdminController

  def new
    @item = AgaDocument.new
  end

  def create
    @item = AgaDocument.new
    set_attributes @item, params[:aga_document]
    @item.user_id = current_user.id
    if @item.save
      respond_to do |format|
        flash! :success
        format.html { redirect_to admin_aga_documents_url }
      end
    else
      respond_to do |format|
        format.html { render "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @item = AgaDocument.where(id: params[:id], user_id: current_user.id).first
  end

  def update
    @item = AgaDocument.find(params[:id])
    set_attributes @item, params[:aga_document]
    if @item.save
      respond_to do |format|
        flash! :success
        format.html { redirect_to admin_aga_documents_url }
      end
    else
      respond_to do |format|
        format.html { render "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    AgaDocument.where(id: params[:id], user_id: current_user.id).first.destroy
    flash[:notice] = t 'label.success_deleted'
    redirect_to action: :index
  end

  def index
    @aga_documents = AgaDocument.order("created_at DESC") rescue ""
=begin
    if current_user.can? :manage, :all
      @aga_documents = AgaDocument.order("created_at DESC") rescue ""
    else
      @aga_documents = AgaDocument.where(user_id: current_user.id).order("created_at DESC") rescue ""
    end
=end
  end

  def set_attributes (item, params)
    item.title = params[:title]
    item.description = params[:description]
    item.datafile = params[:datafile] if params[:datafile].present?
  end

  def namespace
    :admin
  end
  helper_method :namespace

end

app/views/admin/aga_documents/_form.html.haml
= f.text_field :title, class: 'input-xxlarge'
= f.text_area :description, class: 'input-block-level', rows: 2
= f.file_field :datafile
- if @item.datafile.present?
  = link_to "Archivo", @item.datafile.url

app/views/admin/aga_documents/edit.html.haml
= nested_form_for [namespace, @item], builder: BootstrapFormBuilder, html: { class: 'form-horizontal', enctype: 'multipart/form-data'} do |f|
  = field_set_tag t('.title') do
    - if @item.errors.any?
      .alert.alert-error
        %ul
          - @item.errors.full_messages.each do |error|
            %li= error

    = render partial: 'form', locals: { f: f }

    .form-actions
      .btn-group
        = f.button t('label.save'), class: 'btn btn-success btn-large'

app/views/admin/aga_documents/index.html.haml
= render_breadcrumbs

.clearfix
  .pull-left
    %h1
      = "Plan AGA - Documentos Generales"
  .pull-right
    = link_to 'Añadir Documento', new_admin_aga_document_url, class: 'btn btn-primary btn-small'
  .clearfix
  %hr
- if @aga_documents.size > 0
  %table.table.table-condensed.table-hover
    %thead
      %tr
        %th
          Titulo
        %th
          Descripcion
        %th{ colspan: 2 }
    %tbody
      - @aga_documents.each do |f|
        %tr
          %td
            = f.title
          %td
            = f.description.truncate(250, omission: '...')
          %td
            = link_to edit_admin_aga_document_url(f), class: 'btn btn-info btn-small', data: { toggle: 'tooltip', placement: 'top' } do
              %i.icon-pencil=" Editar"
          %td
            = link_to admin_aga_document_url(f), method: :delete, data: { confirm: t('label.confirm_deletion'), toggle: 'tooltip', placement: 'top' }, class: 'btn btn-small btn-danger' do
              %i.icon-trash= " Eliminar"
- else
  .alert.alert-info
    No existen documentos en el registro de Plan AGA

app/views/admin/aga_documents/new.html.haml
= nested_form_for [namespace, @item], builder: BootstrapFormBuilder, html: { class: 'form-horizontal', enctype: 'multipart/form-data'} do |f|
  = field_set_tag t('.title') do
    - if @item.errors.any?
      .alert.alert-error
        %ul
          - @item.errors.full_messages.each do |error|
            %li= error

    = render partial: 'form', locals: { f: f }

    .form-actions
      .btn-group
        = f.button t('label.save'), class: 'btn btn-success btn-large'
        = button_tag class: 'btn dropdown-toggle btn-success btn-large', 'data-toggle' => 'dropdown' do
          %span.caret
        %ul.dropdown-menu
          %li
            = link_to 'Guardar y crear nuevo', 'javascript:void(0)', id: 'save-and-new'