config/routes.rb
PlanAga::Application.routes.draw do
  devise_for :users, controllers: {
               sessions: 'sessions',
               registrations: 'admin/users/new',
            }

  # TinymceFm
  mount TinymceFm::Engine => "/tinymce_fm"

  # constraints :subdomain => 'admin' do
  namespace :admin do
    # scope :module => 'admin', :as => 'admin' do
      # defaults :subdomain => 'admin' do

        root :to => 'dashboard#index'
        resources :users do
          member do
            get :history
          end
        end
        resource :profile
        resources :aga_plans
        resources :aga_responsibles
        resources :aga_challenges do
          collection do
            # get 'general_info'
            # post 'save_general_info'
          end
          resources :aga_actions
        end
        resources :aga_informations
        resources :aga_timeline_items do
          member do
            get 'get_challenge_actions'
          end
        end
        resources :aga_documents
      # end
    # end
  end

  # constraints :subdomain => 'alianza' do
  #   scope :module => 'alianza', :as => 'alianza' do
  #     defaults :subdomain => 'alianza' do
        # root_path = 'aga_challenges#index'
        scope "(:plan)" do
          resources :documents, only: [:index]
          resources :aga_challenges, only: [:index] do
            resources :aga_actions, only: [:show]
            collection do
              get 'general'
              get 'information'
            end
          end
        end
        root :to => 'aga_challenges#index'
        get '/:plan', to: 'aga_challenges#index'
  #     end
  #   end
  # end

  # root :to => 'alianza/aga_challenges#index'
end

app/models/aga_challenge.rb
class AgaChallenge < ActiveRecord::Base
  attr_accessible :aga_plan_id, :title, :color, :description

  has_many :aga_actions, dependent: :destroy
  belongs_to :aga_plan

  extend FriendlyId
  friendly_id :title, :use => :slugged

  validates :title, :description, :aga_plan_id, presence: true

  def full_title
    [aga_plan.title, title].join(' ')
  end

end

app/controllers/admin/aga_challenges_controller.rb
class Admin::AgaChallengesController < AdminController

  def new
    @item = AgaChallenge.new
    @plans = AgaPlan.order('title DESC')
    render layout: false
  end

  def create
    @item = AgaChallenge.new
    set_attributes @item, params[:aga_challenge]
    @success = @item.save
    if @success
      flash.notice = "Se ha creado un nuevo desafio exitosamente"
    else
      @errors = @item.errors.messages.to_json.html_safe
      @plans = AgaPlan.order('title DESC')
    end
  end

  def edit
    @item = AgaChallenge.find(params[:id])
    @plans = AgaPlan.order('title DESC')
    render layout: false
  end

  def update

    @item = AgaChallenge.find(params[:id])
    set_attributes @item, params[:aga_challenge]
    @success = @item.save
    if @success
      flash.notice = "Se ha actualizado el desafio exitosamente"
    else
      @plans = AgaPlan.order('title DESC')
      @errors = @item.errors.messages.to_json.html_safe
    end
  end

  def destroy
    AgaChallenge.find(params[:id]).destroy
    flash[:notice] = t 'label.success_deleted'
    redirect_to admin_aga_challenges_url
  end

  def index
    @challenges = AgaChallenge.all
    @informations = AgaInformation.all
  end

  def general_info
    @aga_information ||= AgaInformation.count > 0 ? AgaInformation.first : AgaInformation.new
  end

  def save_general_info
    @aga_information ||= AgaInformation.count > 0 ? AgaInformation.first : AgaInformation.new
    set_information_attributes(@aga_information, params[:aga_information])
    if @aga_information.save
      flash! :success
      redirect_to admin_aga_challenges_url
    else
      render "general_info"
    end
  end

  def namespace
    :admin
  end
  helper_method :namespace

  def set_attributes (item, params)
    item.title = params[:title]
    item.description = params[:description]
    item.color = params[:color]
    item.aga_plan_id = params[:aga_plan_id]
  end

  def set_information_attributes(item, params)
    item.title = params[:title]
    item.institutions = params[:institutions]
    item.organizations = params[:organizations]
    item.institutions_description = params[:institutions_description]
    item.organizations_description = params[:organizations_description]
    item.general_info = params[:general_info]
    item.plan_description = params[:plan_description]
  end

end

app/controllers/aga_challenges_controller.rb
# encoding: UTF-8
class AgaChallengesController < AlianzaController
  before_filter :average
  respond_to :html

  def index
    @challenges = current_plan.aga_challenges rescue nil
    @aga_information = current_plan.information rescue nil
  end

  def general

  end

  def information
    add_breadcrumb "Inicio", aga_challenges_url
    add_breadcrumb 'Información General'
  	@information = current_plan.information
  end

  def average
    @average ||= AgaAction.where("disabled = ? AND aga_challenge_id IN (?)", 0, current_plan.aga_challenge_ids).average(:percentage).to_f.round(2) rescue "0"
  end
  helper_method :average

end

app/views/admin/aga_challenges/_form.html.haml
= javascript_include_tag "admin/bootstrap-colorpicker.min"

.control-group
  %label.control-label.required{ for: 'aga_challenge_aga_plan_id' }
    Plan
  .controls
    = f.collection_select :aga_plan_id, @plans, :id, :title
= f.text_field :title
= f.text_area :description, rows: 3
= f.text_field :color, class: "colorpicker-element"
:javascript
  $('.colorpicker-element').colorpicker({

  });

app/views/admin/aga_challenges/create.js.erb
<% if @success %>
  window.location.replace("<%= admin_aga_challenges_url %>");
<% else %>
  form = $("form#new_aga_challenge");
  errors = $.parseJSON("<%= j @errors %>");
  new ErrorDisplayer(form, errors);
  <% flash.discard %>
<% end %>

app/views/admin/aga_challenges/edit.html.haml
= nested_form_for [namespace, @item], builder: BootstrapFormBuilder, html: { class: 'form-horizontal', enctype: 'multipart/form-data', remote: true, class: 'edit_aga_challenge' } do |f|
  = field_set_tag t('.title') do
    = render partial: 'form', locals: { f: f }

    .form-actions
      .btn-group
        = f.button t('label.save'), class: 'btn btn-success btn-large'

app/views/admin/aga_challenges/general_info.html.haml
= content_for :scripts do
  = tinymce_javascript_tag 'admin/aga_challenges', 'advanced'
  :javascript
    $(function(){
      tinyMCE.init({
        selector: "textareas",
        mode : "textareas",
        theme : "advanced",
      });
    });

= form_for @aga_information, as: :aga_information, url: save_general_info_admin_aga_challenges_url(@aga_information), method: :post , builder: BootstrapFormBuilder, html: { class: 'form-horizontal', enctype: 'multipart/form-data' } do |f|
  = field_set_tag t('.title') do
    .form-actions
      = f.text_field :title
      = f.text_field :institutions
      = f.text_field :organizations
      = f.text_area :institutions_description, class: 'input-block-level', rows: 4
      = f.text_area :organizations_description, class: 'input-block-level', rows: 4
      = f.text_area :general_info, class: 'input-block-level', rows: 4
      = f.text_area :plan_description, class: 'input-block-level', rows: 4

      .btn-group
        = f.button t('label.save'), class: 'btn btn-success btn-large'

app/views/admin/aga_challenges/index.html.haml
.clearfix
  .pull-left
    %h1
      Plan AGA - Desafíos
  .pull-right
    = link_to 'Crear Desafío', new_admin_aga_challenge_url, class: 'btn btn-primary btn-small fancybox'
- if @challenges.size > 0
  %table.table.table-condensed.table-hover
    %thead
      %tr
        %th
          Plan
        %th
          Desafíos
        %th
          Número de acciones
        %th{ colspan: 3 }
    %tbody
      - @challenges.each do |f|
        %tr
          %td
            = f.aga_plan.try(:title)
          %td
            = f.title
          %td
            = f.aga_actions.count
          %td
            = link_to admin_aga_challenge_aga_actions_url(f), class: 'btn btn-primary btn-small', data: { toggle: 'tooltip', placement: 'top' } do
              %i.icon-eye-open= " Ver acciones"
          %td
            = link_to edit_admin_aga_challenge_url(f), class: 'btn btn-info btn-small fancybox', data: { toggle: 'tooltip', placement: 'top' } do
              %i.icon-pencil=" Editar"
          %td
            = link_to admin_aga_challenge_url(f), method: :delete, data: { confirm: t('label.confirm_deletion'), toggle: 'tooltip', placement: 'top' }, class: 'btn btn-small btn-danger' do
              %i.icon-trash= " Eliminar"
- else
  .alert.alert-info
    No tiene desafíos creados
.clearfix
  .pull-left
    %h1
      Plan AGA - Contenido (Pagina Interna)
  .pull-right
    = link_to 'Crear contenido', new_admin_aga_information_url, class: 'btn btn-primary btn-small'
.clearfix
- if @informations.any?
  %table.table.table-condensed.table-hover
    %thead
      %tr
        %th
          Plan
        %th
          Título
        %th
          Información General
        %th{ colspan: 2 }

    %tbody
      - @informations.each do |info|
        %tr
          %td
            = info.aga_plan.try(:title)
          %td
            = info.title
          %td
            = sanitize info.general_info
          %td
            = link_to edit_admin_aga_information_url(info), class: 'btn btn-info btn-small', data: { toggle: 'tooltip', placement: 'top' } do
              %i.icon-pencil=" Editar"
          %td
            = link_to admin_aga_information_url(info), method: :delete, data: { confirm: t('label.confirm_deletion'), toggle: 'tooltip', placement: 'top' }, class: 'btn btn-small btn-danger' do
              %i.icon-trash= " Eliminar"
- else
  No existe contenido
%br
%br
-# = link_to 'Página de contenido para Plan AGA', general_info_admin_aga_challenges_url, class: 'btn btn-primary btn-small'

app/views/admin/aga_challenges/new.html.haml
= nested_form_for [namespace, @item], builder: BootstrapFormBuilder, html: { class: 'form-horizontal', enctype: 'multipart/form-data', remote: true } do |f|
  = field_set_tag t('.title') do
    = render partial: 'form', locals: { f: f }

    .form-actions
      .btn-group
        = f.button t('label.save'), class: 'btn btn-success btn-large'
        = button_tag class: 'btn dropdown-toggle btn-success btn-large', 'data-toggle' => 'dropdown' do
          %span.caret
        %ul.dropdown-menu
          %li
            = link_to 'Guardar y crear nuevo', 'javascript:void(0)', id: 'save-and-new'

app/views/admin/aga_challenges/update.js.erb
<% if @success %>
  window.location.replace("<%= admin_aga_challenges_url %>");
<% else %>
  form = $("form.edit_aga_challenge");
  errors = $.parseJSON("<%= j @errors %>");
  new ErrorDisplayer(form, errors);
  <% flash.discard %>
<% end %>